// Casos completos para la demostracion. Las fuentes distinguen el material
// docente de los ejemplos del contrato y las pruebas; no se calculan valores
// numericos en el navegador ni se modifican los datos de referencia Python.
//
// Los ejercicios de practica llevan `esperado`: rutas dentro de la respuesta
// de /solve con el valor que tienen que dar. Ninguno salio de correr el
// aplicativo: son formulas cerradas (raiz de 2, cos(x) = x, soluciones
// analiticas de EDO) o la regla de integracion aplicada a mano. La interfaz no
// los usa; los verifica tests/e2e/presets.spec.js contra el servidor real.

const CONFIG_RAICES = {
  decimals: 8,
  max_iterations: 50,
  tolerance: 0.000001,
  error_criterion: "relativo_porcentual",
  stop_on_tolerance: true,
};

const CONFIG_MALLA = { ...CONFIG_RAICES, decimals: 6, stop_on_tolerance: false };

export const PRESETS = [
  {
    id: "newton-clasico",
    metodo: "newton-raphson",
    nombre: "Ejemplo clásico · x³ − 2x − 5",
    fuente: "docs/CONTRATO.md y tests/test_newton_raphson.py",
    descripcion: "Ejemplo clásico del contrato: x₀ = 2. La derivada la calcula el aplicativo.",
    params: { fx: "x^3 - 2*x - 5", x0: 2, dfx: null },
    config: { ...CONFIG_RAICES },
  },
  {
    id: "newton-raiz-de-dos",
    metodo: "newton-raphson",
    nombre: "Práctica · √2 como raíz de x² − 2",
    fuente: "Ejercicio de práctica; la raíz exacta es √2",
    descripcion: "Calcula √2 = 1.41421356 resolviendo x² − 2 = 0 desde x₀ = 1. Converge en pocas iteraciones: el número de decimales correctos casi se duplica en cada paso.",
    params: { fx: "x^2 - 2", x0: 1, dfx: null },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.raiz", valor: 1.4142135623730951, tol: 1e-7 }],
  },
  {
    id: "newton-coseno",
    metodo: "newton-raphson",
    nombre: "Práctica · cos(x) = x",
    fuente: "Ejercicio de práctica; la raíz es el número de Dottie, 0.73908513",
    descripcion: "Función trascendente: cos(x) − x = 0 desde x₀ = 0.5. La raíz es 0.73908513, donde la recta y = x corta al coseno.",
    params: { fx: "cos(x) - x", x0: 0.5, dfx: null },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.raiz", valor: 0.7390851332151607, tol: 1e-7 }],
  },
  {
    id: "newton-derivada-manual",
    metodo: "newton-raphson",
    nombre: "Práctica · e⁻ˣ − x con derivada a mano",
    fuente: "Ejercicio de práctica; la raíz es la constante omega, 0.56714329",
    descripcion: "Se escribe la derivada f′(x) = −e⁻ˣ − 1 en vez de dejar que el aplicativo la calcule. Desde x₀ = 0 llega a 0.56714329.",
    params: { fx: "exp(-x) - x", x0: 0, dfx: "-exp(-x) - 1" },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.raiz", valor: 0.5671432904097838, tol: 1e-7 }],
  },
  {
    id: "newton-ciclo",
    metodo: "newton-raphson",
    nombre: "Práctica · x³ − 2x + 2, el método cicla",
    fuente: "Ejercicio de práctica; ciclo calculado a mano: f(0)/f′(0) = −1 y f(1)/f′(1) = 1",
    descripcion: "Desde x₀ = 0 la sucesión salta 0 → 1 → 0 → 1 sin acercarse a la única raíz real, −1.76929235. Muestra que Newton-Raphson no siempre converge. Corre 10 iteraciones; probar con x₀ = −2 para ver que sí llega.",
    params: { fx: "x^3 - 2*x + 2", x0: 0, dfx: null },
    config: { ...CONFIG_RAICES, max_iterations: 10 },
    esperado: [
      { ruta: "converged", valor: false },
      { ruta: "result.raiz", valor: 0, tol: 0 },
    ],
  },
  {
    id: "newton-plastico",
    metodo: "newton-raphson",
    nombre: "Práctica · x³ − x − 1",
    fuente: "Ejercicio de práctica; la raíz es el número plástico, 1.32471796",
    descripcion: "Cúbica con una sola raíz real. Desde x₀ = 1.5 llega a 1.32471796 en pocas iteraciones.",
    params: { fx: "x^3 - x - 1", x0: 1.5, dfx: null },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.raiz", valor: 1.324717957244746, tol: 1e-7 }],
  },
  {
    id: "newton-logaritmo",
    metodo: "newton-raphson",
    nombre: "Práctica · ln(x) = 1, calcular e",
    fuente: "Ejercicio de práctica; la raíz exacta es e = 2.71828183",
    descripcion: "ln(x) − 1 = 0 desde x₀ = 2. La raíz es el número e, 2.71828183. El aplicativo deriva f′(x) = 1/x.",
    params: { fx: "ln(x) - 1", x0: 2, dfx: null },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.raiz", valor: Math.E, tol: 1e-7 }],
  },
  {
    id: "newton-raiz-doble",
    metodo: "newton-raphson",
    nombre: "Práctica · raíz doble (x − 1)²",
    fuente: "Ejercicio de práctica; a mano: x(i+1) = (x(i) + 1)/2, así que xᵢ = 1 + 2⁻ⁱ",
    descripcion: "En una raíz doble f′ también se anula y Newton-Raphson pierde su rapidez: desde x₀ = 2 el error solo se divide entre 2 en cada paso. Necesita 27 iteraciones para la tolerancia; comparar con las pocas que usa √2, que es una raíz simple.",
    params: { fx: "(x - 1)^2", x0: 2, dfx: null },
    config: { ...CONFIG_RAICES },
    esperado: [
      { ruta: "result.raiz", valor: 1, tol: 1e-6 },
      { ruta: "result.iteraciones", valor: 27 },
    ],
  },
  {
    id: "von-mises-docente",
    metodo: "von-mises",
    nombre: "Docente · e⁻ˣ − ln(x)",
    fuente: "VON MISES.pdf, diapositiva 7; tests/casos_referencia.py",
    descripcion: "Caso resuelto del docente: x₀ = 1, con la derivada congelada en el punto inicial.",
    params: { fx: "exp(-x) - log(x)", x0: 1, dfx: null },
    config: { ...CONFIG_RAICES },
  },
  {
    id: "von-mises-divergente",
    metodo: "von-mises",
    nombre: "Docente · ejercicio divergente",
    fuente: "VON MISES.pdf, diapositiva 10; tests/casos_referencia.py",
    descripcion: "Ejercicio propuesto: 4x³ − 18x² + 12x − 6, x₀ = 1.165. Con Von Mises diverge; se muestra la causa.",
    params: { fx: "4*x**3 - 18*x**2 + 12*x - 6", x0: 1.165, dfx: null },
    config: { ...CONFIG_RAICES },
  },
  {
    id: "von-mises-raiz-de-dos",
    metodo: "von-mises",
    nombre: "Práctica · √2 con la derivada congelada",
    fuente: "Ejercicio de práctica; la raíz exacta es √2",
    descripcion: "x² − 2 = 0 desde x₀ = 1.5, con f′(1.5) = 3 fijo. Converge a 1.41421356 porque f′ cambia poco entre x₀ y la raíz. Comparar con Newton-Raphson para ver cuántas iteraciones más necesita.",
    params: { fx: "x^2 - 2", x0: 1.5, dfx: null },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.raiz", valor: 1.4142135623730951, tol: 1e-7 }],
  },
  {
    id: "von-mises-coseno",
    metodo: "von-mises",
    nombre: "Práctica · cos(x) = x",
    fuente: "Ejercicio de práctica; la raíz es el número de Dottie, 0.73908513",
    descripcion: "cos(x) − x = 0 desde x₀ = 0.5, con la derivada congelada en f′(0.5) = −1.47942554. Llega a 0.73908513, el mismo valor que Newton-Raphson.",
    params: { fx: "cos(x) - x", x0: 0.5, dfx: null },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.raiz", valor: 0.7390851332151607, tol: 1e-7 }],
  },
  {
    id: "von-mises-exponencial",
    metodo: "von-mises",
    nombre: "Práctica · e⁻ˣ − x",
    fuente: "Ejercicio de práctica; la raíz es la constante omega, 0.56714329",
    descripcion: "e⁻ˣ − x = 0 desde x₀ = 0, con f′(0) = −2 congelada. Llega a 0.56714329. Con el mismo ejercicio en Newton-Raphson se comparan las dos tablas.",
    params: { fx: "exp(-x) - x", x0: 0, dfx: null },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.raiz", valor: 0.5671432904097838, tol: 1e-7 }],
  },
  {
    id: "von-mises-plastico",
    metodo: "von-mises",
    nombre: "Práctica · x³ − x − 1",
    fuente: "Ejercicio de práctica; la raíz es el número plástico, 1.32471796",
    descripcion: "Desde x₀ = 1.5 con f′(1.5) = 5.75 congelada. En la raíz f′ vale 4.26, así que el factor |1 − 4.26/5.75| ≈ 0.26 es menor que 1 y converge a 1.32471796.",
    params: { fx: "x^3 - x - 1", x0: 1.5, dfx: null },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.raiz", valor: 1.324717957244746, tol: 1e-7 }],
  },
  {
    id: "von-mises-logaritmo",
    metodo: "von-mises",
    nombre: "Práctica · ln(x) = 1, calcular e",
    fuente: "Ejercicio de práctica; la raíz exacta es e = 2.71828183",
    descripcion: "ln(x) − 1 = 0 desde x₀ = 2.5, con f′(2.5) = 0.4 congelada. Como f′(e) = 0.368 está cerca de 0.4, converge rápido a 2.71828183.",
    params: { fx: "ln(x) - 1", x0: 2.5, dfx: null },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.raiz", valor: Math.E, tol: 1e-7 }],
  },
  {
    id: "von-mises-fibonacci",
    metodo: "von-mises",
    nombre: "Práctica · x³ + 2x² + 10x − 20 (Fibonacci)",
    fuente: "Ejercicio de práctica; la cúbica que resolvió Fibonacci en 1225, raíz 1.36880811",
    descripcion: "Desde x₀ = 1 con f′(1) = 17 congelada. Converge a 1.36880811, el valor que Fibonacci calculó a mano con nueve cifras.",
    params: { fx: "x^3 + 2*x^2 + 10*x - 20", x0: 1, dfx: null },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.raiz", valor: 1.3688081078213727, tol: 1e-7 }],
  },
  {
    id: "interpolacion-logaritmo",
    metodo: "interpolacion-newton",
    nombre: "Ejemplo del contrato · ln(2)",
    fuente: "docs/CONTRATO.md",
    descripcion: "Interpola los puntos (1, 0), (4, 1.386294) y (6, 1.791759) en x = 2, con diferencias divididas.",
    params: { points: [[1, 0], [4, 1.386294], [6, 1.791759]], x: 2, variante: "divididas" },
    config: { ...CONFIG_RAICES },
  },
  {
    id: "interpolacion-newton-docente",
    metodo: "interpolacion-newton",
    nombre: "Docente · (1,2) (0,4) (−3,−2)",
    fuente: "Interpolación del método de Newton.pdf, diapositivas 5-8",
    descripcion: "Ejercicio resuelto en clase. Da P(x) = −x² − x + 4 y lo evalúa en x = −4, donde vale −8. Los puntos van en el orden del pizarrón: no se ordenan por x.",
    params: { points: [[1, 2], [0, 4], [-3, -2]], x: -4, variante: "divididas" },
    config: { ...CONFIG_RAICES },
  },
  {
    id: "interpolacion-cuadratica",
    metodo: "interpolacion-newton",
    nombre: "Demo · puntos equiespaciados",
    fuente: "tests/test_newton_interpolation.py",
    descripcion: "Caso de prueba resuelto a mano: (0, 1), (1, 2), (2, 5). Evalúa en x = 3 y elige diferencias hacia adelante.",
    params: { points: [[0, 1], [1, 2], [2, 5]], x: 3, variante: "auto" },
    config: { ...CONFIG_RAICES },
  },
  {
    id: "interpolacion-newton-cubica",
    metodo: "interpolacion-newton",
    nombre: "Práctica · cuatro puntos de x³ − 2x + 1",
    fuente: "Ejercicio de práctica; los puntos salen de f(x) = x³ − 2x + 1",
    descripcion: "Los puntos (−1, 2), (0, 1), (1, 0), (2, 5) están sobre x³ − 2x + 1, así que el polinomio interpolante tiene que ser exactamente ese. En x = 3 vale 22.",
    params: { points: [[-1, 2], [0, 1], [1, 0], [2, 5]], x: 3, variante: "divididas" },
    config: { ...CONFIG_RAICES },
    esperado: [
      { ruta: "result.valor", valor: 22, tol: 1e-9 },
      { ruta: "result.grado", valor: 3 },
    ],
  },
  {
    id: "interpolacion-newton-raiz",
    metodo: "interpolacion-newton",
    nombre: "Práctica · aproximar √5 con (1,1) (4,2) (9,3)",
    fuente: "Ejercicio de práctica; diferencias divididas a mano: 1/3, 1/5 y −1/60",
    descripcion: "Puntos de √x sin espaciado constante. P(x) = (−x² + 25x + 36)/60 y P(5) = 34/15 ≈ 2.26666667, contra √5 ≈ 2.23606798: se ve el error de interpolar una función que no es polinomio.",
    params: { points: [[1, 1], [4, 2], [9, 3]], x: 5, variante: "divididas" },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.valor", valor: 34 / 15, tol: 1e-9 }],
  },
  {
    id: "interpolacion-newton-atras",
    metodo: "interpolacion-newton",
    nombre: "Práctica · diferencias hacia atrás",
    fuente: "Ejercicio de práctica; los puntos salen de f(x) = 2x² + 1",
    descripcion: "Puntos equiespaciados (0, 1), (1, 3), (2, 9), (3, 19) con la variante hacia atrás. La tabla cambia, pero el polinomio sigue siendo 2x² + 1 y en x = 2.5 vale 13.5.",
    params: { points: [[0, 1], [1, 3], [2, 9], [3, 19]], x: 2.5, variante: "atras" },
    config: { ...CONFIG_RAICES },
    esperado: [
      { ruta: "result.valor", valor: 13.5, tol: 1e-9 },
      { ruta: "result.grado", valor: 2 },
      { ruta: "result.variante_usada", valor: "atras" },
    ],
  },
  {
    id: "interpolacion-newton-adelante",
    metodo: "interpolacion-newton",
    nombre: "Práctica · diferencias hacia adelante",
    fuente: "Ejercicio de práctica; los puntos salen de f(x) = x² + 2x − 1",
    descripcion: "Puntos equiespaciados (1, 2), (2, 7), (3, 14), (4, 23) con la variante hacia adelante. Las segundas diferencias son constantes (2), por eso el polinomio es de grado 2: x² + 2x − 1, que en x = 2.5 vale 10.25.",
    params: { points: [[1, 2], [2, 7], [3, 14], [4, 23]], x: 2.5, variante: "adelante" },
    config: { ...CONFIG_RAICES },
    esperado: [
      { ruta: "result.valor", valor: 10.25, tol: 1e-9 },
      { ruta: "result.grado", valor: 2 },
      { ruta: "result.variante_usada", valor: "adelante" },
    ],
  },
  {
    id: "interpolacion-newton-inversa",
    metodo: "interpolacion-newton",
    nombre: "Práctica · aproximar 1/3 con puntos de 1/x",
    fuente: "Ejercicio de práctica; diferencias divididas a mano: −1/2, −1/8 y 1/8",
    descripcion: "Puntos (1, 1), (2, 0.5), (4, 0.25) de f(x) = 1/x. P(x) = 1 − 0.5(x − 1) + 0.125(x − 1)(x − 2) y P(3) = 0.25, contra 1/3 ≈ 0.33333: un error grande por usar pocos puntos de una curva que no es polinomio.",
    params: { points: [[1, 1], [2, 0.5], [4, 0.25]], x: 3, variante: "divididas" },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.valor", valor: 0.25, tol: 1e-9 }],
  },
  {
    id: "lagrange-docente",
    metodo: "interpolacion-lagrange",
    nombre: "Docente · (0,1) (1,3) (2,0)",
    fuente: "INTERPOLACIÓN DE LAGRANGE.pdf, diapositivas 5-7",
    descripcion: "Primer ejercicio resuelto en clase. Da P(x) = −5/2 x² + 9/2 x + 1. La tabla muestra cada L₍ᵢ₎ con su numerador y su denominador.",
    params: { points: [[0, 1], [1, 3], [2, 0]], x: 1.5 },
    config: { ...CONFIG_RAICES },
  },
  {
    id: "lagrange-docente-2",
    metodo: "interpolacion-lagrange",
    nombre: "Docente · (1,3) (2,5) (3,1)",
    fuente: "INTERPOLACIÓN DE LAGRANGE.pdf, diapositivas 8-9",
    descripcion: "Segundo ejercicio resuelto, con el procedimiento de cinco pasos escrito completo. Da P(x) = −3x² + 11x − 5.",
    params: { points: [[1, 3], [2, 5], [3, 1]], x: 2.5 },
    config: { ...CONFIG_RAICES },
  },
  {
    id: "lagrange-ejercicio",
    metodo: "interpolacion-lagrange",
    nombre: "Docente · ejercicio propuesto",
    fuente: "INTERPOLACIÓN DE LAGRANGE.pdf, diapositiva 10",
    descripcion: "Ejercicio propuesto, sin resolver en clase: (1,10), (−4,10), (−7,34), interpolando en x = −3. Da P(x) = x² + 3x + 6 y P(−3) = 6.",
    params: { points: [[1, 10], [-4, 10], [-7, 34]], x: -3 },
    config: { ...CONFIG_RAICES },
  },
  {
    id: "lagrange-recta",
    metodo: "interpolacion-lagrange",
    nombre: "Práctica · dos puntos, una recta",
    fuente: "Ejercicio de práctica; la recta por (2, 5) y (6, 13) es y = 2x + 1",
    descripcion: "El caso más chico: con dos puntos hay dos polinomios base, L₀ = (x − 6)/(2 − 6) y L₁ = (x − 2)/(6 − 2). Su combinación es la recta 2x + 1, que en x = 3 vale 7.",
    params: { points: [[2, 5], [6, 13]], x: 3 },
    config: { ...CONFIG_RAICES },
    esperado: [
      { ruta: "result.valor", valor: 7, tol: 1e-9 },
      { ruta: "result.grado", valor: 1 },
    ],
  },
  {
    id: "lagrange-cubica",
    metodo: "interpolacion-lagrange",
    nombre: "Práctica · cuatro puntos de x³ − 2x + 1",
    fuente: "Ejercicio de práctica; los puntos salen de f(x) = x³ − 2x + 1",
    descripcion: "Los mismos cuatro puntos del ejercicio de Newton: (−1, 2), (0, 1), (1, 0), (2, 5). Cuatro polinomios base de grado 3 y el mismo resultado, P(3) = 22: el polinomio interpolante es único.",
    params: { points: [[-1, 2], [0, 1], [1, 0], [2, 5]], x: 3 },
    config: { ...CONFIG_RAICES },
    esperado: [
      { ruta: "result.valor", valor: 22, tol: 1e-9 },
      { ruta: "result.grado", valor: 3 },
    ],
  },
  {
    id: "lagrange-raiz",
    metodo: "interpolacion-lagrange",
    nombre: "Práctica · aproximar √5 con (1,1) (4,2) (9,3)",
    fuente: "Ejercicio de práctica; P(x) = (−x² + 25x + 36)/60, verificado en los tres puntos",
    descripcion: "Puntos de √x. P(5) = 34/15 ≈ 2.26666667, igual que con Newton, contra √5 ≈ 2.23606798.",
    params: { points: [[1, 1], [4, 2], [9, 3]], x: 5 },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.valor", valor: 34 / 15, tol: 1e-9 }],
  },
  {
    id: "lagrange-inversa",
    metodo: "interpolacion-lagrange",
    nombre: "Práctica · aproximar 1/3 con puntos de 1/x",
    fuente: "Ejercicio de práctica; P(x) = 1 − 0.5(x − 1) + 0.125(x − 1)(x − 2), verificado en los tres puntos",
    descripcion: "Los mismos puntos (1, 1), (2, 0.5), (4, 0.25) del ejercicio de Newton. P(3) = 0.25, igual que con Newton, contra el valor real 1/3.",
    params: { points: [[1, 1], [2, 0.5], [4, 0.25]], x: 3 },
    config: { ...CONFIG_RAICES },
    esperado: [{ ruta: "result.valor", valor: 0.25, tol: 1e-9 }],
  },
  {
    id: "lagrange-cubo",
    metodo: "interpolacion-lagrange",
    nombre: "Práctica · cuatro puntos de x³",
    fuente: "Ejercicio de práctica; los puntos salen de f(x) = x³",
    descripcion: "Puntos (−1, −1), (0, 0), (2, 8), (3, 27). Como y₁ = 0, el término de L₁ se anula, pero los otros tres reconstruyen x³ exacto: en x = 1 vale 1.",
    params: { points: [[-1, -1], [0, 0], [2, 8], [3, 27]], x: 1 },
    config: { ...CONFIG_RAICES },
    esperado: [
      { ruta: "result.valor", valor: 1, tol: 1e-9 },
      { ruta: "result.grado", valor: 3 },
    ],
  },
  {
    id: "runge-kutta-escalar",
    metodo: "runge-kutta",
    nombre: "Ejemplo del contrato · y′ = x + y",
    fuente: "docs/CONTRATO.md",
    descripcion: "Ecuación escalar: y(0) = 1, h = 0.1, cinco pasos hasta x = 0.5, Runge-Kutta de orden 4.",
    params: { fxy: "x + y", x0: 0, y0: 1, h: 0.1, n: 5, xf: null, orden: 4 },
    config: { ...CONFIG_MALLA },
  },
  {
    id: "runge-kutta-sistema",
    metodo: "runge-kutta",
    nombre: "Demo · oscilador de dos EDO",
    fuente: "tests/test_runge_kutta.py, la prueba del oscilador hasta x = 1.6",
    descripcion: "Sistema y₁′ = y₂, y₂′ = −y₁; y₁(0) = 1, y₂(0) = 0. Dieciséis pasos de 0.1 para observar el cruce por cero.",
    params: { fxy: ["y2", "-y1"], x0: 0, y0: [1, 0], h: 0.1, n: 16, xf: null, orden: 4 },
    config: { ...CONFIG_MALLA },
  },
  {
    id: "runge-kutta-decaimiento",
    metodo: "runge-kutta",
    nombre: "Práctica · decaimiento y′ = −2y",
    fuente: "Ejercicio de práctica; solución exacta y = e^(−2x); RK4 multiplica cada paso por 1 + z + z²/2 + z³/6 + z⁴/24 con z = −0.2",
    descripcion: "y(0) = 1, h = 0.1, diez pasos hasta x = 1. La solución exacta es e⁻² = 0.13533528; RK4 da 0.13533955, un error de 4 × 10⁻⁶.",
    params: { fxy: "-2*y", x0: 0, y0: 1, h: 0.1, n: 10, xf: null, orden: 4 },
    config: { ...CONFIG_MALLA },
    esperado: [{ ruta: "result.y", valor: 0.13533954843051027, tol: 1e-12 }],
  },
  {
    id: "runge-kutta-heun",
    metodo: "runge-kutta",
    nombre: "Práctica · Heun (orden 2) con y′ = y",
    fuente: "Ejercicio de práctica; Heun multiplica cada paso por 1 + h + h²/2 = 1.105",
    descripcion: "y(0) = 1 hasta x = 1 con h = 0.1, definiendo la malla con h y x final. Heun da 1.105¹⁰ = 2.71408085 contra e = 2.71828183. Cambiar el orden a 4 para ver cuánto mejora.",
    params: { fxy: "y", x0: 0, y0: 1, h: 0.1, n: null, xf: 1, orden: 2 },
    config: { ...CONFIG_MALLA },
    esperado: [
      { ruta: "result.y", valor: 2.714080846608224, tol: 1e-12 },
      { ruta: "result.n", valor: 10 },
    ],
  },
  {
    id: "runge-kutta-xy",
    metodo: "runge-kutta",
    nombre: "Práctica · y′ = x·y con n y x final",
    fuente: "Ejercicio de práctica; solución exacta y = e^(x²/2)",
    descripcion: "y(0) = 1 hasta x = 1 en cinco pasos: el aplicativo calcula h = 0.2. La solución exacta en x = 1 es e^(1/2) = 1.64872127.",
    params: { fxy: "x*y", x0: 0, y0: 1, h: null, n: 5, xf: 1, orden: 4 },
    config: { ...CONFIG_MALLA },
    esperado: [
      { ruta: "result.y", valor: 1.6487212707001282, tol: 1e-5 },
      { ruta: "result.h", valor: 0.2, tol: 1e-12 },
    ],
  },
  {
    id: "runge-kutta-hiperbolico",
    metodo: "runge-kutta",
    nombre: "Práctica · sistema y₁′ = y₂, y₂′ = y₁",
    fuente: "Ejercicio de práctica; solución exacta y₁ = cosh x, y₂ = senh x",
    descripcion: "El primo del oscilador, con el signo cambiado: las soluciones crecen en vez de oscilar. y₁(0) = 1, y₂(0) = 0, diez pasos de 0.1. En x = 1: cosh 1 = 1.54308063 y senh 1 = 1.17520119.",
    params: { fxy: ["y2", "y1"], x0: 0, y0: [1, 0], h: 0.1, n: 10, xf: null, orden: 4 },
    config: { ...CONFIG_MALLA },
    esperado: [
      { ruta: "result.y.0", valor: 1.5430806348152437, tol: 1e-5 },
      { ruta: "result.y.1", valor: 1.1752011936438014, tol: 1e-5 },
    ],
  },
  {
    id: "runge-kutta-enfriamiento",
    metodo: "runge-kutta",
    nombre: "Práctica · ley de enfriamiento de Newton",
    fuente: "Ejercicio de práctica; solución exacta y = 20 + 70e^(−x/2); RK4 multiplica (y − 20) por 1 + z + z²/2 + z³/6 + z⁴/24 con z = −0.25",
    descripcion: "Un café a 90 °C en una sala a 20 °C: y′ = −0.5(y − 20), y(0) = 90, h = 0.5, diez pasos. A los 5 minutos la temperatura exacta es 25.74595 °C y RK4 da 25.74653 °C.",
    params: { fxy: "-0.5*(y - 20)", x0: 0, y0: 90, h: 0.5, n: 10, xf: null, orden: 4 },
    config: { ...CONFIG_MALLA },
    esperado: [{ ruta: "result.y", valor: 25.746526197308203, tol: 1e-9 }],
  },
  {
    id: "runge-kutta-logistica",
    metodo: "runge-kutta",
    nombre: "Práctica · crecimiento logístico",
    fuente: "Ejercicio de práctica; solución exacta y = 1/(1 + 9e^(−x))",
    descripcion: "Una población que se satura: y′ = y(1 − y), y(0) = 0.1, h = 0.2, diez pasos hasta x = 2. La solución exacta es 0.45085306 y RK4 queda a menos de 2 × 10⁻⁶.",
    params: { fxy: "y*(1 - y)", x0: 0, y0: 0.1, h: 0.2, n: 10, xf: null, orden: 4 },
    config: { ...CONFIG_MALLA },
    esperado: [{ ruta: "result.y", valor: 0.4508530603792838, tol: 1e-5 }],
  },
  {
    id: "punto-medio-docente",
    metodo: "punto-medio",
    nombre: "Docente · ∫(0.25x³ − x) de −1.5 a 2",
    fuente: "MÉTODO DE INTEGRACIÓN DEL PUNTO MEDIO.pdf, ejemplo del parcial 1",
    descripcion: "Ejemplo del docente: integra 0.25x³ − x entre −1.5 y 2 con n = 7 rectángulos. El valor real es −0.1914; el método aproxima −0.2051.",
    params: { fx: "0.25*x^3 - x", a: -1.5, b: 2, n: 7 },
    config: { ...CONFIG_MALLA, decimals: 4 },
  },
  {
    id: "punto-medio-refinado",
    metodo: "punto-medio",
    nombre: "Demo · mismo ejercicio con n = 100",
    fuente: "MÉTODO DE INTEGRACIÓN DEL PUNTO MEDIO.pdf; refinamiento de la malla",
    descripcion: "Mismo integrando, mismo intervalo, con cien rectángulos: el resultado se acerca al valor exacto −0.1914 y se ve cómo el error baja al refinar la malla.",
    params: { fx: "0.25*x^3 - x", a: -1.5, b: 2, n: 100 },
    config: { ...CONFIG_MALLA },
  },
  {
    id: "punto-medio-parabola",
    metodo: "punto-medio",
    nombre: "Práctica · ∫x² de 0 a 3",
    fuente: "Ejercicio de práctica; seis rectángulos a mano: 0.5 · (0.25² + 0.75² + … + 2.75²)",
    descripcion: "El valor exacto es 9. Con n = 6 el punto medio da 8.9375: se queda corto por 0.0625. Compararlo con el mismo ejercicio en Trapecio, que se pasa por el doble.",
    params: { fx: "x^2", a: 0, b: 3, n: 6 },
    config: { ...CONFIG_MALLA },
    esperado: [{ ruta: "result.integral", valor: 8.9375, tol: 1e-12 }],
  },
  {
    id: "punto-medio-seno",
    metodo: "punto-medio",
    nombre: "Práctica · ∫sen(x) de 0 a π",
    fuente: "Ejercicio de práctica; valor exacto 2, cuatro rectángulos a mano",
    descripcion: "Media onda del seno con n = 4: da 2.05234431 contra el valor exacto 2. Como el seno es cóncavo en [0, π], el punto medio se pasa.",
    params: { fx: "sin(x)", a: 0, b: Math.PI, n: 4 },
    config: { ...CONFIG_MALLA, decimals: 8 },
    esperado: [{ ruta: "result.integral", valor: 2.052344305954062, tol: 1e-12 }],
  },
  {
    id: "punto-medio-gauss",
    metodo: "punto-medio",
    nombre: "Práctica · ∫e^(−x²) de 0 a 1",
    fuente: "Ejercicio de práctica; valor exacto (√π/2)·erf(1) = 0.74682413",
    descripcion: "Una integral sin primitiva elemental: por eso hacen falta métodos numéricos. Con n = 10 da 0.74713088 contra 0.74682413.",
    params: { fx: "exp(-x^2)", a: 0, b: 1, n: 10 },
    config: { ...CONFIG_MALLA, decimals: 8 },
    esperado: [{ ruta: "result.integral", valor: 0.7471308777479975, tol: 1e-12 }],
  },
  {
    id: "punto-medio-logaritmo",
    metodo: "punto-medio",
    nombre: "Práctica · ∫1/x de 1 a 2 = ln 2",
    fuente: "Ejercicio de práctica; valor exacto ln 2 = 0.69314718, cuatro rectángulos a mano",
    descripcion: "Con n = 4 los puntos medios son 1.125, 1.375, 1.625 y 1.875: da 0.69121989 contra ln 2 = 0.69314718. Comparar con el mismo ejercicio en Trapecio.",
    params: { fx: "1/x", a: 1, b: 2, n: 4 },
    config: { ...CONFIG_MALLA, decimals: 8 },
    esperado: [{ ruta: "result.integral", valor: 0.6912198912198912, tol: 1e-12 }],
  },
  {
    id: "punto-medio-raiz",
    metodo: "punto-medio",
    nombre: "Práctica · ∫√x de 0 a 4",
    fuente: "Ejercicio de práctica; valor exacto 16/3 = 5.33333333",
    descripcion: "Con n = 8 da 5.35225738 contra 16/3. El punto medio nunca evalúa en x = 0, donde √x tiene pendiente infinita.",
    params: { fx: "sqrt(x)", a: 0, b: 4, n: 8 },
    config: { ...CONFIG_MALLA, decimals: 8 },
    esperado: [{ ruta: "result.integral", valor: 5.352257377040016, tol: 1e-12 }],
  },
  {
    id: "punto-medio-recta",
    metodo: "punto-medio",
    nombre: "Práctica · ∫(3x + 2) de 1 a 4, exacto",
    fuente: "Ejercicio de práctica; primitiva 1.5x² + 2x: (24 + 8) − (1.5 + 2) = 28.5",
    descripcion: "Para una recta el punto medio es exacto con cualquier n: lo que sobra a un lado del rectángulo falta al otro. Con n = 3 da 28.5, el valor exacto.",
    params: { fx: "3*x + 2", a: 1, b: 4, n: 3 },
    config: { ...CONFIG_MALLA },
    esperado: [{ ruta: "result.integral", valor: 28.5, tol: 1e-12 }],
  },
  {
    id: "trapecio-docente",
    metodo: "trapecio",
    nombre: "Docente · ∫eˣ⁴ de −1 a 1",
    fuente: "Métodos de Integración Numérica.MÉTODO DEL TRAPECIO.pdf, caso n = 5",
    descripcion: "Ejemplo del docente: integra eˣ⁴ entre −1 y 1 con cinco trapecios. El paso es 0.4 y la aproximación es 2.79929211.",
    params: { fx: "exp(x^4)", a: -1, b: 1, n: 5 },
    config: { ...CONFIG_MALLA, decimals: 8 },
  },
  {
    id: "trapecio-simple",
    metodo: "trapecio",
    nombre: "Docente · un trapecio en [−1, 1]",
    fuente: "Métodos de Integración Numérica.MÉTODO DEL TRAPECIO.pdf, caso n = 1",
    descripcion: "El mismo integrando con n = 1. Usa solo los extremos y deja visible por qué una malla más fina mejora la aproximación.",
    params: { fx: "exp(x^4)", a: -1, b: 1, n: 1 },
    config: { ...CONFIG_MALLA, decimals: 8 },
  },
  {
    id: "trapecio-parabola",
    metodo: "trapecio",
    nombre: "Práctica · ∫x² de 0 a 3",
    fuente: "Ejercicio de práctica; siete puntos a mano con pesos 1, 2, 2, 2, 2, 2, 1",
    descripcion: "El valor exacto es 9. Con n = 6 el trapecio da 9.125: se pasa por 0.125, el doble de lo que se queda corto el punto medio (8.9375) y con el signo contrario.",
    params: { fx: "x^2", a: 0, b: 3, n: 6 },
    config: { ...CONFIG_MALLA },
    esperado: [{ ruta: "result.integral", valor: 9.125, tol: 1e-12 }],
  },
  {
    id: "trapecio-seno",
    metodo: "trapecio",
    nombre: "Práctica · ∫sen(x) de 0 a π",
    fuente: "Ejercicio de práctica; valor exacto 2, cinco puntos a mano",
    descripcion: "Media onda del seno con n = 4: da 1.89611890 contra 2. Las cuerdas quedan debajo de una curva cóncava, así que el trapecio se queda corto.",
    params: { fx: "sin(x)", a: 0, b: Math.PI, n: 4 },
    config: { ...CONFIG_MALLA, decimals: 8 },
    esperado: [{ ruta: "result.integral", valor: 1.8961188979370398, tol: 1e-12 }],
  },
  {
    id: "trapecio-logaritmo",
    metodo: "trapecio",
    nombre: "Práctica · ∫1/x de 1 a 2 = ln 2",
    fuente: "Ejercicio de práctica; valor exacto ln 2 = 0.69314718",
    descripcion: "Con n = 4: (0.25/2)·[1 + 2(0.8 + 0.666667 + 0.571429) + 0.5] = 0.69702381, contra ln 2 = 0.69314718.",
    params: { fx: "1/x", a: 1, b: 2, n: 4 },
    config: { ...CONFIG_MALLA, decimals: 8 },
    esperado: [{ ruta: "result.integral", valor: 0.6970238095238095, tol: 1e-12 }],
  },
  {
    id: "trapecio-gauss",
    metodo: "trapecio",
    nombre: "Práctica · ∫e^(−x²) de 0 a 1",
    fuente: "Ejercicio de práctica; valor exacto (√π/2)·erf(1) = 0.74682413",
    descripcion: "Con n = 10 da 0.74621080, un poco por debajo de 0.74682413. El mismo ejercicio en Punto Medio queda un poco por encima.",
    params: { fx: "exp(-x^2)", a: 0, b: 1, n: 10 },
    config: { ...CONFIG_MALLA, decimals: 8 },
    esperado: [{ ruta: "result.integral", valor: 0.7462107961317495, tol: 1e-12 }],
  },
  {
    id: "trapecio-raiz",
    metodo: "trapecio",
    nombre: "Práctica · ∫√x de 0 a 4",
    fuente: "Ejercicio de práctica; valor exacto 16/3 = 5.33333333",
    descripcion: "Con n = 8 da 5.26504177 contra 16/3. Converge más lento que con funciones suaves porque √x tiene pendiente infinita en x = 0.",
    params: { fx: "sqrt(x)", a: 0, b: 4, n: 8 },
    config: { ...CONFIG_MALLA, decimals: 8 },
    esperado: [{ ruta: "result.integral", valor: 5.265041772995635, tol: 1e-12 }],
  },
  {
    id: "trapecio-recta",
    metodo: "trapecio",
    nombre: "Práctica · ∫(3x + 2) de 1 a 4, exacto",
    fuente: "Ejercicio de práctica; primitiva 1.5x² + 2x: (24 + 8) − (1.5 + 2) = 28.5",
    descripcion: "Para una recta el trapecio es exacto con cualquier n: el segmento coincide con la función. Con n = 3 da 28.5, el valor exacto.",
    params: { fx: "3*x + 2", a: 1, b: 4, n: 3 },
    config: { ...CONFIG_MALLA },
    esperado: [{ ruta: "result.integral", valor: 28.5, tol: 1e-12 }],
  },
];

export function presetsPara(slug) {
  return PRESETS.filter(preset => preset.metodo === slug);
}
